### ISSUE TITLE
Quitting while playback is paused takes several seconds

### ISSUE THREAD

**Issue by Markus00000** [cmus/cmus#1064]
cmus exits instantly when playback is on while quitting:

1. `$ CMUS_HOME=/tmp/cmus /usr/bin/cmus`
2. Play MP3 file
3. `:q` exits cmus and `cmus` terminates almost instantly

Exiting cmus while playback is paused takes several seconds:

1. `$ CMUS_HOME=/tmp/cmus /usr/bin/cmus`
2. Play MP3 file
3. Pause playback
4. `:q` closes the cmus interface, but `cmus` will keep running for several seconds before terminating

This problem only appeared recently.

---

1) `uname -a`:
```
Linux lati 5.11.6-arch1-1 #1 SMP PREEMPT Thu, 11 Mar 2021 13:48:23 +0000 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao

```

**Comment by pgaskin** [comment]
I can't reproduce this on `v2.8.0` or `v2.9.1` with `ffmpeg 4.3.2-0+deb11u1`. How many playlists do you have, and how large is your library?

**Comment by Markus00000** [comment]
I tested with no playlists and an empty library by setting `CMUS_HOME=/tmp/cmus`.

I copied a single MP3 to `/tmp/cmus` and started playback using the browser.

**Comment by pgaskin** [comment]
Can you upload your `/use/bin/cmus`,  `/usr/lib/cmus/ip/mad.so`, and 
 `/usr/lib/cmus/ip/ffmpeg.so` so I can test those directly? Also, can I see the output of `ffmpeg` without any arguments?

**Comment by Markus00000** [comment]
The requested files: [cmus-1064.zip](https://github.com/cmus/cmus/files/6151645/cmus-1064.zip)

It happens with any audio file I have tested. Including `.flac`, `.m4a` and `.ogg` files.

    $ ffmpeg
    ffmpeg version n4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
      built with gcc 10.2.0 (GCC)
      configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-shared --enable-version3
      libavutil      56. 51.100 / 56. 51.100
      libavcodec     58. 91.100 / 58. 91.100
      libavformat    58. 45.100 / 58. 45.100
      libavdevice    58. 10.100 / 58. 10.100
      libavfilter     7. 85.100 /  7. 85.100
      libswscale      5.  7.100 /  5.  7.100
      libswresample   3.  7.100 /  3.  7.100
      libpostproc    55.  7.100 / 55.  7.100
    Hyper fast Audio and Video encoder
    usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
    
    Use -h to get full help or, even better, run 'man ffmpeg'

**Comment by KookiesGH** [comment]
Hello. Like to add that I'm also getting the same problem as Markus, except with opus files instead of mp3: closing during playback is fine, but closing while paused will take much longer. 

`uname -a`
```
Linux marshmallow 5.11.6-138-tkg-pds #1 TKG SMP PREEMPT Wed, 17 Mar 2021 05:31:59 +0000 x86_64 GNU/Linux
```
`cmus --version`
```
cmus v2.9.1-1-ga9ac3de
```
`cmus --plugins`
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao
```

Here's an archive with `/usr/bin/cmus`, `/usr/lib/cmus/ip/opus.so/`, and `/usr/lib/cmus/ip/ffmpeg.so`: [cmus-debug-kookies.tar.gz](https://github.com/cmus/cmus/files/6176354/cmus-debug-kookies.tar.gz)

**Comment by pgaskin** [comment]
Hmm. That's interesting. I'll see if I can figure out what's common between the two formats while exiting when I have time.

**Comment by Markus00000** [comment]
> figure out what's common between the two formats

Not sure if I am misunderstanding what you mean by *two* formats, however, the affected formats from this thread so far are:

* .mp3
* .flac
* .m4a
* .ogg
* .opus

Maybe it is independent of the format.

Could it be related to PipeWire? I think the problem started around the time PipeWire replaced PulseAudio on my system.

**Comment by KookiesGH** [comment]
You make a good point. I also have the PipeWire pulse replacement on my computer, but I swear the same problem happens on my chromebook with regular pulseaudio installed. I'll do some more testing on it and report back.

**Comment by KookiesGH** [comment]
So as it turns out, this does seem to be a problem exclusive to PipeWire. No matter how much I tried to induce the same problem on the chromebook, I always got a fast exit regardless if cmus was paused or playing.

**Comment by Zambito1** [comment]
I am also having this issue. I am running PipeWire 0.3.24, and cmus v2.8.0.

**Comment by pgaskin** [comment]
> So as it turns out, this does seem to be a problem exclusive to PipeWire

That's very helpful to know. It would have been one of the last things I'd have looked at, since I don't use PipeWire myself, it's meant to be a drop-in replacement, and the PulseAudio API is relatively simple.

I'll have to take a closer look at PipeWire's behaviour later and learn how it works internally.

In the meantime, it might be a good idea to report this to the PipeWire project itself, since the problem is at least partly due to it.

**Comment by KookiesGH** [comment]
I'll submit something to the PipeWire guys about it. Thanks for your help!

**Comment by nefthy** [comment]
There is a [fix in PipeWire repo](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/fa1350b0cf30f0965d739141b845535294c02238)

**Comment by pgaskin** [comment]
I'm going to close this now that the fix has been released and is in most distros with PipeWire.

Also, BTW, I now use PipeWire myself since it's implemented network support, the echo cancel plugin, and a few other features I need. It's also a lot more stable then it used to be when I tried it last year.

**Comment by Konglomneshued** [comment]
I still have this issue:
![image](https://user-images.githubusercontent.com/94726665/206935356-0e4a61f7-669c-4936-8876-8f04b3ba3ec4.png)

When quitting while no audio playing or paused:
![image](https://user-images.githubusercontent.com/94726665/206935367-b3ecb166-a6d6-4d56-8a6c-3071749813b8.png)

**Comment by fkranhold** [comment]
I am still experiencing that issue as well, with cmus 2.10.0-4 and pipewire 1:10.7-2 on arch. (In addition to that, hitting v for stop while pausing the playback entirely freezes cmus.)

**Comment by Vamp898** [comment]
I can confirm this issue on Gentoo and Archlinux, it is not fixed. On all my machines, when paused, quitting cmus takes sometimes half a minute.

Stopping music beforehand and it quits instantly. It doesn't matter if i use :q or the interactive method pressing q and replying with y

**Comment by gavtroy** [comment]
It was only fixed in 2.11. For reference the Arch package is still 2.10.
