### ISSUE TITLE
OS X: Does not reconnect to bluetooth headphones on disconnect and reconnect

### ISSUE THREAD

**Issue by samdmarshall** [cmus/cmus#653]
This issue presents in a very similar manner to https://github.com/cmus/cmus/issues/481, with the exception that it is happening with bluetooth headphones rather than USB. If I start up cmus while I have the headphones connected, I can play audio to them. if I disconnect from them, then playback switches over to my laptop's speakers. This is all expected behavior based on my system audio settings. If i now reconnect to my bluetooth headphones, then audio from cmus continues to play over the speakers while all other audio from the system is playing back over the headphones. I was able to reproduce this on HEAD from master as well as in 2.7.1. 

The bluetooth headphones in question are apple AirPods, and the audio resume works correctly in all other applications so I have no reason to suspect that there is something broken or irregular with how the audio device handling is done. Also I've double checked my system audio settings while reproducing this and on reconnect the system output device switches from speakers to the headphones automatically.
---

1) `uname -a`:
```
Darwin Tolva.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
```

2) `cmus --version`:
```
cmus c64e0d5
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/HEAD-c64e0d5_2/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/HEAD-c64e0d5_2/lib/cmus/op
  coreaudio
  ao
```

**Comment by samdmarshall** [comment]
Update: I didn't realize this before, but if i open cmus, then connect to the headphone; cmus' audio still comes out of my speakers, not the headphones. I need to connect to the headphones prior to opening cmus, which is behavior unique to cmus as far as I can tell.

**Comment by samdmarshall** [comment]
I think I have isolated this behavior to some weirdness with the CoreAudio APIs and these headphones. Right now I am confident that this is a bug (and not an enhancement) in the way that the CoreAudio plugin is written that fails to connect to this audio output source when the system connects to it as the new "default". I'll try to update this again once I have more information.

**Comment by flyingmutant** [comment]
CCing @Wang-Yue, as he is the author of the CoreAudio plugin.

**Comment by samdmarshall** [comment]
Another update to this: it appears that when queried by CoreAudio for output sources, it shows two outputs of the same name, presumably one for each AirPod. So unlike other audio output sources, where there is only one, there may be more involved in connecting and using these sources because merely connecting to one of them in some sample code i had kicking around produces an error (which presumably the CoreAudio plugin also experiences). This may also be why the output of cmus doesn't switch from the last output source to the AirPods as it encounters this error/failure and then falls back to the existing usable source.

**Comment by samdmarshall** [comment]
@flyingmutant @Wang-Yue any update on this?

**Comment by Wang-Yue** [comment]
if someone can fix https://github.com/cmus/cmus/issues/600 I can take a look at this issue.

**Comment by absurd** [comment]
> shows two outputs of the same name, presumably one for each AirPod. So unlike other audio output sources, where there is only one, there may be more involved in connecting and using these sources

I'm seeing the same behavior with both Jaybird X2 and X3 headphones and my build lacks the coreaudio output plugin completely.

**Comment by setphen** [comment]
I'm experiencing this issue, too. My headphones are the Bose QC35 II. Any updates?

**Comment by EpicOrange** [comment]
I'm also experiencing the exact described problem on OSX High Sierra with the Bose SoundLink Micro Speaker. It's more of an annoyance than anything since the issue is solved by restarting cmus.

**Comment by davidwoodburn** [comment]
Okay, the problem is still here. Are we just not going to address it?
